export const SOURCES = [
  { id: "arbeitnow", name: "Arbeitnow", type: "json", endpoint: "https://www.arbeitnow.com/api/job-board-api" },
  { id: "jobicy", name: "Jobicy", type: "json", endpoint: "https://jobicy.com/api/v2/remote-jobs" },
  { id: "remoteok", name: "Remote OK", type: "json", endpoint: "https://remoteok.com/api" },
  { id: "remotive", name: "Remotive", type: "json", endpoint: "https://remotive.com/api/remote-jobs" },
  { id: "himalayas", name: "Himalayas", type: "json", endpoint: "https://himalayas.app/jobs/api" },
  { id: "nodesk", name: "NoDesk", type: "json", endpoint: "https://nodesk.co/remote-jobs/feed.json" },
  { id: "remote4me", name: "Remote4Me", type: "json", endpoint: "https://remote4me.com/api/jobs" },
  { id: "jobspresso", name: "Jobspresso", type: "json", endpoint: "https://jobspresso.co/remote-jobs.json" },
  { id: "dailyremote", name: "Daily Remote", type: "json", endpoint: "https://dailyremote.com/api/jobs" },
  { id: "remotees", name: "Remotees", type: "json", endpoint: "https://remotees.com/api/jobs" },
  { id: "justremote", name: "JustRemote", type: "json", endpoint: "https://justremote.co/api/jobs" },
  { id: "workingnomads", name: "Working Nomads", type: "json", endpoint: "https://www.workingnomads.com/api/jobs" },
  { id: "weworkremotely", name: "We Work Remotely", type: "json", endpoint: "https://weworkremotely.com/api/jobs" },
  { id: "remote-co", name: "Remote.co", type: "json", endpoint: "https://remote.co/remote-jobs.json" },
  { id: "flexjobs", name: "FlexJobs", type: "json", endpoint: "https://www.flexjobs.com/api/jobs" },
  { id: "job-board-search", name: "Job Board Search", type: "json", endpoint: "https://jobboardsearch.com/api/jobs" },
  { id: "startup-jobs", name: "Startup Jobs", type: "json", endpoint: "https://startup.jobs/api/jobs" },
  { id: "remote-leads", name: "Remote Leads", type: "json", endpoint: "https://remoteleads.io/api/jobs" },
  { id: "eures", name: "EURES", type: "json", endpoint: "https://ec.europa.eu/eures/api/jobs" },
  { id: "jobbank-canada", name: "Job Bank Canada", type: "json", endpoint: "https://www.jobbank.gc.ca/api/jobs" },
  { id: "jobsearch-australia", name: "JobSearch Australia", type: "json", endpoint: "https://api.jobsearch.gov.au/jobs" },
  { id: "uk-government", name: "UK Government Jobs", type: "json", endpoint: "https://findajob.dwp.gov.uk/api/jobs" },
  { id: "usa-jobs", name: "USAJOBS", type: "json", endpoint: "https://data.usajobs.gov/api/Search" },
  { id: "european-jobday", name: "European Job Day", type: "json", endpoint: "https://www.europeanjobdays.eu/api/jobs" },
  { id: "government-jobs", name: "GovernmentJobs", type: "json", endpoint: "https://www.governmentjobs.com/api/jobs" },
  { id: "dice", name: "Dice", type: "json", endpoint: "https://www.dice.com/jobs/api" },
  { id: "wellfound", name: "Wellfound", type: "json", endpoint: "https://wellfound.com/jobs/api" },
  { id: "otta", name: "Otta", type: "json", endpoint: "https://otta.com/api/jobs" },
  { id: "ycombinator", name: "Y Combinator", type: "json", endpoint: "https://ycombinator.com/api/jobs" },
  { id: "workatastartup", name: "Work at a Startup", type: "json", endpoint: "https://www.workatastartup.com/api/jobs" },
  { id: "greenhouse-google", name: "Google (Greenhouse)", type: "ats", endpoint: "https://boards-api.greenhouse.io/v1/boards/google/jobs" },
  { id: "greenhouse-microsoft", name: "Microsoft (Greenhouse)", type: "ats", endpoint: "https://boards-api.greenhouse.io/v1/boards/microsoft/jobs" },
  { id: "greenhouse-airbnb", name: "Airbnb (Greenhouse)", type: "ats", endpoint: "https://boards-api.greenhouse.io/v1/boards/airbnb/jobs" },
  { id: "greenhouse-stripe", name: "Stripe (Greenhouse)", type: "ats", endpoint: "https://boards-api.greenhouse.io/v1/boards/stripe/jobs" },
  { id: "lever-github", name: "GitHub (Lever)", type: "ats", endpoint: "https://api.lever.co/v0/postings/github?mode=json" },
  { id: "lever-netflix", name: "Netflix (Lever)", type: "ats", endpoint: "https://api.lever.co/v0/postings/netflix?mode=json" },
  { id: "lever-shopify", name: "Shopify (Lever)", type: "ats", endpoint: "https://api.lever.co/v0/postings/shopify?mode=json" },
  { id: "ashby-dropbox", name: "Dropbox (Ashby)", type: "ats", endpoint: "https://api.ashbyhq.com/posting-api/job-board/dropbox" },
  { id: "ashby-figma", name: "Figma (Ashby)", type: "ats", endpoint: "https://api.ashbyhq.com/posting-api/job-board/figma" },
  { id: "ashby-notion", name: "Notion (Ashby)", type: "ats", endpoint: "https://api.ashbyhq.com/posting-api/job-board/notion" },
];
export function getSources() {
  return SOURCES.filter(s => s.type === "json" || s.type === "rss");
}
